apiVersion: v1
kind: Pod
metadata:
  name: api-gateway
  labels:
    role: api-gateway
spec:
  containers:
    - name: api-gateway
      image: mqsr/greenmile-api-gateway:1.0.0
      imagePullPolicy: Always
      ports:
        - name: api-gateway
          containerPort: 8080
          hostPort: 8080
          protocol: TCP
      volumeMounts:
        - name: config-volume
          mountPath: /app/config/env.ini
          subPath: env.ini
      restartPolicy: Always
  volumes:
    - name: config-volume
      configMap:
        name: appsettings-configmap
  