services:
  rabbitmq:
    image: rabbitmq:3.12.14-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: ${SQLSERVER_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - '1433:1433'