services:
  greenmilesharing.api:
    image: greenmilesharing.api
    build:
      context: .
      dockerfile: GreenMileSharing.API/Dockerfile

  greenmilesharing.identityapi:
    image: greenmilesharing.identityapi
    build:
      context: .
      dockerfile: GreenMileSharing.IdentityApi/Dockerfile

  greenmilesharing.emailservice:
    image: greenmilesharing.emailservice
    build:
      context: .
      dockerfile: GreenMileSharing.EmailService/Dockerfile
      
  rabbitmq:
    image: rabbitmq:3.12.14-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  
  identityDb:
    image: postgres:16.0-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
  
  tripsDb:
    image: postgres:16.0-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
