apiVersion: v1
kind: Service
metadata:
  name: identity-api
  labels:
    app: payment-service
spec:
  selector:
    app: identity-api
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  type: ClusterIP
  