apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-api
  labels:
    app: identity-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-api
  template:
    metadata:
      name: identity-api
      labels:
        app: identity-api
    spec:
      containers:
        - name: identity-api
          image: mqsr/greenmile-identity-api:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /app/config/env.ini
              subPath: env.ini
      restartPolicy: Always
      volumes:
          - name: config-volume
            configMap:
              name: appsettings-configmap
      